#!/bin/zsh

assert() {
    if [[ $# == 1 || "$2" != "$3" ]]; then
	echo "Failure: $1"
	ERR=1
	if [[ "$2" != "$3" ]]; then echo "\tExpected: $3\n\tReceived: $2"; fi
    fi
}

function teardown() {
    cd "$DIR"
    rm -rf inbox md5 text notes bib
}

AMD5=$(md5sum <<< 'a' | cut -f1 -d' ')
BMD5=$(md5sum <<< 'b' | cut -f1 -d' ')

KB=$(realpath ./kb)
DIR=$(mktemp -d)
trap "rm -rf $DIR" EXIT
cd "$DIR"

assert 'bad file structure' "$($KB ingest 2>&1)" 'kb directory structure not detected. Use "kb init" to create a new directory structure.'

$KB init
echo 'a' > inbox/a.pdf
echo 'b' > inbox/b.txt

#ingest
$KB ingest
[[ -f inbox/a.pdf ]] && assert 'ingest inbox a'
[[ -f inbox/b.txt ]] && assert 'ingest inbox b'
[[ -f md5/$AMD5.pdf ]] || assert 'ingest m5d a'
[[ -f md5/$BMD5.txt ]] || assert 'ingest m5d b  '
[[ -f bib/$AMD5.bib ]] || assert 'ingest bib a'
[[ -f bib/$BMD5.bib ]] || assert 'ingest bib b'
[[ -f notes/$AMD5.org ]] || assert 'ingest org a'
assert 'ingest org link' "$(head -n1 notes/$AMD5.org)" '[file:../md5/'"$AMD5"'.pdf][link]'
[[ -f notes/$BMD5.org ]] || assert 'ingest org b'
assert 'ingest title' "$(cat bib/$AMD5.bib)" "$(echo 'title\ta')"

#ls
assert 'ls' "$($KB ls)" "$(echo 'b\na')"



[[ -z "$ERR" ]] && echo "All Tests Pass"
exit "$ERR"
